from __future__ import annotations

import cv2
import mujoco
import numpy as np

from .env import SO101PushEnv


def poly_features(uv: np.ndarray) -> np.ndarray:
    a = np.asarray(uv, np.float32)
    single = a.ndim == 1
    x = a[None] if single else a
    u, v = x[:, 0], x[:, 1]
    f = np.stack(
        [np.ones_like(u), u, v, u*u, u*v, v*v], axis=1
    )
    return f[0] if single else f


def look_quat(view_dir: np.ndarray, up_ref=np.array([1.0, 0.0, 0.0])) -> np.ndarray:
    d = np.asarray(view_dir, float)
    d /= np.linalg.norm(d)
    z = -d
    up = np.asarray(up_ref, float)
    y = up - z * np.dot(up, z)
    if np.linalg.norm(y) < 1e-6:
        up = np.array([0.0, 1.0, 0.0])
        y = up - z * np.dot(up, z)
    y /= np.linalg.norm(y)
    x = np.cross(y, z)
    x /= np.linalg.norm(x)
    R = np.column_stack([x, y, z])
    q = np.empty(4, float)
    mujoco.mju_mat2Quat(q, R.reshape(-1))
    return q


def configure_offset_wrist_camera(env: SO101PushEnv) -> None:
    """Move the simulated wrist camera to a side-offset eye-in-hand mount.

    In our 48-pose visibility sweep, the stock mount saw the cube in 38/48
    poses. This side-offset mount saw it in 48/48.
    """
    b = env.model
    cid = b.camera("wrist_camera").id
    cam_pos = np.array([0.040, -0.035, -0.050])
    grasp = np.array([-0.0079, 0.0095, -0.0981274])
    b.cam_pos[cid] = cam_pos
    b.cam_quat[cid] = look_quat(grasp - cam_pos)
    mujoco.mj_forward(env.model, env.data)


class GlobalBootstrapDetector:
    """One-shot color-agnostic object localization from overhead RGB.

    The manipulated object is discovered as the changed component between the
    current RGB frame and an empty-scene RGB frame. The detector is used only
    once per episode before the robot moves into the workspace.

    In simulation the empty frame is generated by temporarily moving the object
    out of view. On a real robot the analogue is a cached empty-table frame.
    """

    def __init__(self, env: SO101PushEnv, width=320, height=240) -> None:
        self.env = env
        self.renderer = mujoco.Renderer(env.model, height=height, width=width)
        self.cam = mujoco.MjvCamera()
        mujoco.mjv_defaultCamera(self.cam)
        self.cam.type = mujoco.mjtCamera.mjCAMERA_FREE
        self.cam.lookat[:] = [0.23, 0.0, 0.02]
        self.cam.distance = 0.52
        self.cam.azimuth = 90
        self.cam.elevation = -90
        self.world_w: np.ndarray | None = None
        self._calibrate()

    def render(self) -> np.ndarray:
        self.renderer.update_scene(self.env.data, camera=self.cam)
        return self.renderer.render().copy()

    def empty_frame(self) -> np.ndarray:
        addr = self.env._cube_joint_addresses["red_cube"]
        saved = self.env.data.qpos[addr:addr+7].copy()
        saved_vel = self.env.data.qvel.copy()
        self.env.write_cube_pose(
            "red_cube", np.array([0.60, 0.60, self.env.cube_half_size])
        )
        mujoco.mj_forward(self.env.model, self.env.data)
        image = self.render()
        self.env.data.qpos[addr:addr+7] = saved
        self.env.data.qvel[:] = saved_vel
        mujoco.mj_forward(self.env.model, self.env.data)
        return image

    @staticmethod
    def discover_centroid(current: np.ndarray, empty: np.ndarray) -> np.ndarray | None:
        diff = np.mean(
            np.abs(current.astype(np.float32) - empty.astype(np.float32)),
            axis=2,
        )
        diff = cv2.GaussianBlur(diff, (5, 5), 0)
        nz = diff[diff > 1.0]
        if len(nz) < 8:
            return None

        threshold = max(7.0, float(np.percentile(nz, 75)))
        mask = (diff >= threshold).astype(np.uint8) * 255
        mask = cv2.morphologyEx(
            mask, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8)
        )
        n, labels, stats, _ = cv2.connectedComponentsWithStats(mask, 8)

        candidates = []
        for i in range(1, n):
            x, y, w, h, area = stats[i]
            if 12 <= area <= 2000 and w <= 60 and h <= 60:
                candidates.append((float(diff[labels == i].mean()), i))
        if not candidates:
            return None

        _, idx = max(candidates)
        x, y, w, h, _ = stats[idx]
        return np.array([x + w / 2.0, y + h / 2.0], np.float32)

    def _pixel(self) -> np.ndarray | None:
        return self.discover_centroid(self.render(), self.empty_frame())

    def _calibrate(self) -> None:
        addr = self.env._cube_joint_addresses["red_cube"]
        saved = self.env.data.qpos[addr:addr+7].copy()
        saved_vel = self.env.data.qvel.copy()

        pixels, world = [], []
        for y in np.linspace(-0.11, 0.11, 6):
            for x in np.linspace(0.15, 0.31, 6):
                self.env.write_cube_pose(
                    "red_cube", np.array([x, y, self.env.cube_half_size])
                )
                mujoco.mj_forward(self.env.model, self.env.data)
                uv = self._pixel()
                if uv is not None:
                    pixels.append(uv)
                    world.append([x, y])

        self.env.data.qpos[addr:addr+7] = saved
        self.env.data.qvel[:] = saved_vel
        mujoco.mj_forward(self.env.model, self.env.data)

        X = poly_features(np.asarray(pixels, np.float32))
        Y = np.asarray(world, np.float32)
        self.world_w = np.linalg.lstsq(X, Y, rcond=None)[0]

    def locate(self) -> np.ndarray:
        uv = self._pixel()
        if uv is None or self.world_w is None:
            raise RuntimeError("global object bootstrap failed")
        return (poly_features(uv) @ self.world_w).astype(np.float32)

    def close(self) -> None:
        self.renderer.close()



class HighPrecisionGlobalDetector(GlobalBootstrapDetector):
    """Tighter overhead detector for pick-and-place workspaces.

    It uses the same color-agnostic current-vs-empty idea as
    GlobalBootstrapDetector but fits a denser calibration over the smaller
    pick-and-place workspace and scores components by total RGB residual.
    """

    @staticmethod
    def discover_centroid(
        current: np.ndarray,
        empty: np.ndarray,
    ) -> np.ndarray | None:
        diff = np.linalg.norm(
            current.astype(np.float32) - empty.astype(np.float32),
            axis=2,
        )
        diff = cv2.GaussianBlur(diff, (3, 3), 0)
        nz = diff[diff > 2.0]
        if len(nz) < 8:
            return None

        threshold = max(10.0, float(np.percentile(nz, 65)))
        mask = (diff >= threshold).astype(np.uint8) * 255
        mask = cv2.morphologyEx(
            mask, cv2.MORPH_CLOSE, np.ones((3, 3), np.uint8)
        )
        n, labels, stats, _ = cv2.connectedComponentsWithStats(mask, 8)

        candidates: list[tuple[float, int]] = []
        for i in range(1, n):
            x, y, w, h, area = stats[i]
            if 8 <= area <= 2200 and w <= 70 and h <= 70:
                candidates.append((float(diff[labels == i].sum()), i))
        if not candidates:
            return None

        _, idx = max(candidates)
        x, y, w, h, _ = stats[idx]
        return np.asarray([x + w / 2, y + h / 2], dtype=np.float32)

    def _calibrate(self) -> None:
        address = self.env._cube_joint_addresses["red_cube"]
        saved_qpos = self.env.data.qpos[address : address + 7].copy()
        saved_qvel = self.env.data.qvel.copy()
        geom_id = self.env._cube_geom_ids["red_cube"]
        saved_rgba = self.env.model.geom_rgba[geom_id].copy()

        # Calibration target appearance is irrelevant at runtime; using a
        # high-contrast target makes the geometric fit less noisy.
        self.env.model.geom_rgba[geom_id] = (0.85, 0.12, 0.10, 1.0)

        pixels: list[np.ndarray] = []
        world: list[list[float]] = []
        for y in np.linspace(-0.10, 0.08, 7):
            for x in np.linspace(0.19, 0.29, 7):
                self.env.write_cube_pose(
                    "red_cube",
                    np.asarray([x, y, self.env.cube_half_size]),
                )
                mujoco.mj_forward(self.env.model, self.env.data)
                uv = self._pixel()
                if uv is not None:
                    pixels.append(uv)
                    world.append([x, y])

        self.env.data.qpos[address : address + 7] = saved_qpos
        self.env.data.qvel[:] = saved_qvel
        self.env.model.geom_rgba[geom_id] = saved_rgba
        mujoco.mj_forward(self.env.model, self.env.data)

        X = poly_features(np.asarray(pixels, np.float32))
        Y = np.asarray(world, np.float32)
        self.world_w = np.linalg.lstsq(X, Y, rcond=None)[0]


class WristAppearanceTracker:
    """Moving-camera tracker for the contact phase.

    A wrist ROI is predicted from the global object estimate and camera
    geometry. The tracker learns an HSV appearance model from that ROI; there
    is no hard-coded object color. Runtime tracking is local around the
    reprojected previous world estimate, compensating for camera motion.
    """

    def __init__(self, env: SO101PushEnv, width=320, height=240) -> None:
        self.env = env
        self.w = width
        self.h = height
        self.renderer = mujoco.Renderer(
            env.model, height=height, width=width
        )
        self.cid = env.model.camera("wrist_camera").id
        self.fovy = np.deg2rad(float(env.model.cam_fovy[self.cid]))
        self.focal = 0.5 * height / np.tan(0.5 * self.fovy)
        self.hist: np.ndarray | None = None
        self.last_world: np.ndarray | None = None
        self.failures = 0

    def render(self) -> np.ndarray:
        self.renderer.update_scene(self.env.data, camera="wrist_camera")
        return self.renderer.render().copy()

    def project_world(self, xyz: np.ndarray) -> np.ndarray | None:
        pos = self.env.data.cam_xpos[self.cid].copy()
        R = self.env.data.cam_xmat[self.cid].reshape(3, 3).copy()
        q = R.T @ (np.asarray(xyz, float) - pos)
        depth = -float(q[2])
        if depth <= 1e-5:
            return None
        return np.array(
            [
                self.w / 2 + self.focal * float(q[0]) / depth,
                self.h / 2 - self.focal * float(q[1]) / depth,
            ],
            np.float32,
        )

    def ray_to_plane(self, uv: np.ndarray, z_plane: float) -> np.ndarray | None:
        pos = self.env.data.cam_xpos[self.cid].copy()
        R = self.env.data.cam_xmat[self.cid].reshape(3, 3).copy()
        d_cam = np.array(
            [
                (float(uv[0]) - self.w / 2) / self.focal,
                -(float(uv[1]) - self.h / 2) / self.focal,
                -1.0,
            ]
        )
        d = R @ d_cam
        if abs(float(d[2])) < 1e-6:
            return None
        t = (float(z_plane) - float(pos[2])) / float(d[2])
        if t <= 0:
            return None
        return (pos + t * d).astype(np.float32)

    def reset(self) -> None:
        self.hist = None
        self.last_world = None

    def bootstrap(self, expected_xy: np.ndarray) -> bool:
        image = self.render()
        uv = self.project_world(
            np.array([expected_xy[0], expected_xy[1], self.env.cube_half_size])
        )
        if uv is None:
            return False
        if not (5 <= uv[0] < self.w - 5 and 5 <= uv[1] < self.h - 5):
            return False

        radius = 18
        x0 = max(0, int(uv[0] - radius))
        y0 = max(0, int(uv[1] - radius))
        x1 = min(self.w, int(uv[0] + radius + 1))
        y1 = min(self.h, int(uv[1] + radius + 1))

        hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
        roi = hsv[y0:y1, x0:x1]
        if roi.size == 0:
            return False

        yy, xx = np.mgrid[0:roi.shape[0], 0:roi.shape[1]]
        cx, cy = uv[0] - x0, uv[1] - y0
        mask = (((xx-cx)**2 + (yy-cy)**2) <= radius**2).astype(np.uint8) * 255
        mask = cv2.bitwise_and(
            mask,
            (((roi[..., 1] > 25) & (roi[..., 2] > 35)).astype(np.uint8) * 255),
        )

        hist = cv2.calcHist(
            [roi], [0, 1], mask, [24, 24], [0, 180, 0, 256]
        )
        if float(hist.sum()) <= 1:
            return False
        cv2.normalize(hist, hist, 0, 255, cv2.NORM_MINMAX)
        self.hist = hist
        self.last_world = np.asarray(expected_xy, np.float32).copy()
        return True

    def track(self) -> np.ndarray:
        if self.hist is None or self.last_world is None:
            raise RuntimeError("wrist tracker has not been bootstrapped")

        image = self.render()
        pred_uv = self.project_world(
            np.array(
                [self.last_world[0], self.last_world[1], self.env.cube_half_size]
            )
        )
        if pred_uv is None:
            self.failures += 1
            return self.last_world.copy()

        hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
        back = cv2.calcBackProject(
            [hsv], [0, 1], self.hist, [0, 180, 0, 256], 1
        ).astype(np.float32)

        yy, xx = np.mgrid[0:self.h, 0:self.w]
        d2 = (xx-pred_uv[0])**2 + (yy-pred_uv[1])**2
        score = back * np.exp(-d2 / (2 * 36.0**2))

        x0 = max(0, int(pred_uv[0] - 52))
        y0 = max(0, int(pred_uv[1] - 52))
        x1 = min(self.w, int(pred_uv[0] + 53))
        y1 = min(self.h, int(pred_uv[1] + 53))
        crop = score[y0:y1, x0:x1]
        if crop.size == 0 or float(crop.max()) < 2.0:
            self.failures += 1
            return self.last_world.copy()

        q = float(np.percentile(crop, 88))
        cy, cx = np.nonzero(crop >= max(q, 2.0))
        if len(cx) < 4:
            self.failures += 1
            return self.last_world.copy()

        weights = crop[cy, cx] + 1e-3
        u = float((weights * (cx+x0)).sum() / weights.sum())
        v = float((weights * (cy+y0)).sum() / weights.sum())
        world = self.ray_to_plane(
            np.array([u, v], np.float32), self.env.cube_half_size
        )
        if world is None:
            self.failures += 1
            return self.last_world.copy()

        xy = world[:2]
        if np.linalg.norm(xy - self.last_world) > 0.035:
            self.failures += 1
            return self.last_world.copy()

        self.last_world = (
            0.80 * xy + 0.20 * self.last_world
        ).astype(np.float32)
        return self.last_world.copy()

    def close(self) -> None:
        self.renderer.close()
